### ISSUE TITLE
10 - Pause Stage STATE Considerations

### ISSUE THREAD

**Issue by malakivandas** [MECH458-B02-Group2/mech458-final-project#10]
State is set to 0 when unpaused.

BUT it won't re-enter the stage previous to pausing.

Fix this and consider other considerations

**Comment by malakivandas** [comment]
// Pause button
ISR(INT4_vect) {

	//Home board debugging purposes
	mTimer(20); // debounce
	
	if(STATE == 4) {
		STATE = 0; // will goto POLLING_STAGE
	}
	else {
		STATE = 4; // will goto PAUSE_STAGE
	}
} // Pause

**Comment by raimullin** [comment]
Don't need to change state now that its in an ISR because when the ISR is completed it will just go back to wherever it was previously
