### ISSUE TITLE
14 - Pause Button moved to ISR

### ISSUE THREAD

**Issue by raimullin** [MECH458-B02-Group2/mech458-final-project#14]
Can still have other ISRs trigger while paused, need to remove that. Want to:
 - Make the ISR trigger when the button is pressed 
 - Stay in the ISR using a while (button not pressed)
 - Then while(button is pressed) - wait for button to be released the second time
 - Now we finally exit the ISR

**Comment by malakivandas** [comment]
Moved pause functionality to ISR(INT4)
Interrupts do not trigger during pause state

**Comment by malakivandas** [comment]
Prepared for lab apparatus testing

**Comment by malakivandas** [comment]
Worked in lab apparatus
