### ISSUE TITLE
6 - Stepper Acceleration

### ISSUE THREAD

**Issue by malakivandas** [MECH458-B02-Group2/mech458-final-project#6]

**Comment by raimullin** [comment]
Implemented, needs to be tested

**Comment by raimullin** [comment]
Working on our steppers, need to optimize on their stepper

**Comment by raimullin** [comment]
Lot of work had to be done, wrote some unnecessary functions but ended up pre-declaring the curves in an array and calling those array values in an iterative mTimer, works well and the curve can be edited in the mainheader file
