### ISSUE TITLE
7 - LCD Display

### ISSUE THREAD

**Issue by malakivandas** [MECH458-B02-Group2/mech458-final-project#7]
Pause
Counting pieces
Amount of pieces on belt
Amount sorted

**Comment by raimullin** [comment]
Completed and verified :)

**Comment by raimullin** [comment]
jk

**Comment by malakivandas** [comment]
lol

**Comment by malakivandas** [comment]
After RAMP DOWN display what had been sorted

**Comment by raimullin** [comment]
Finalized and simplified LCD output to pause stage, rampdown, and an initial active display
