### ISSUE TITLE
9 - Reflective Stage while() alternative

### ISSUE THREAD

**Issue by malakivandas** [MECH458-B02-Group2/mech458-final-project#9]
while((PIND & 0b00000100) == 0b00000100) { 
		ADCSRA |= _BV(ADSC); // Take another ADC reading
		if (ADC_result>reflect_val) {
			reflect_val = ADC_result;
		} // Overwrite previous value if bigger
	}
	// Malaki - noticing that this while loop blocks other functionality
	// eg. while there is a piece in front of the optical sensor, the system will not pause

**Comment by raimullin** [comment]
Not of concern according to Simon and Patrick -> Also changed it to an if statement and it continuously goes into the ADC complete ISR
